#!/usr/bin/env node

/**
 * clawsig init — First-run scaffolding for the Clawsig Protocol.
 *
 * Creates a .clawsig/ directory with:
 * - identity.json  — Ed25519 key pair (JWK) + derived did:key
 * - config.json    — Starter verifier config (trusts own DID)
 * - README.md      — Quick orientation
 *
 * Safe to re-run: skips if .clawsig/ already exists (unless --force).
 */

import fs from 'node:fs';
import path from 'node:path';
import {
  generateKeyPair,
  didFromPublicKey,
  exportKeyPairJWK,
} from './crypto.js';

// ── CLI args ────────────────────────────────────────────────────

const args = process.argv.slice(2);
const force = args.includes('--force');
const quiet = args.includes('--quiet') || args.includes('-q');
const dir = path.resolve(process.cwd(), '.clawsig');

function log(msg: string): void {
  if (!quiet) process.stdout.write(`${msg}\n`);
}

// ── Main ────────────────────────────────────────────────────────

async function main(): Promise<void> {
  if (fs.existsSync(dir) && !force) {
    log(`✓ .clawsig/ already exists. Use --force to regenerate.`);
    // Print the existing DID for convenience
    try {
      const id = JSON.parse(fs.readFileSync(path.join(dir, 'identity.json'), 'utf8'));
      log(`  DID: ${id.did}`);
    } catch { /* ignore */ }
    return;
  }

  log('Initializing .clawsig/...\n');

  // 1. Generate key pair
  const keyPair = await generateKeyPair();
  const did = await didFromPublicKey(keyPair.publicKey);
  const jwk = await exportKeyPairJWK(keyPair);

  fs.mkdirSync(dir, { recursive: true });

  // 2. Write identity.json
  const identity = {
    did,
    algorithm: 'Ed25519',
    created_at: new Date().toISOString(),
    public_key: jwk.publicKey,
    private_key: jwk.privateKey,
  };
  const identityPath = path.join(dir, 'identity.json');
  fs.writeFileSync(identityPath, JSON.stringify(identity, null, 2) + '\n');
  log(`  ✓ identity.json  → ${did}`);

  // 3. Write config.json (trusts own DID for self-verification)
  const config = {
    config_version: '1' as const,
    created_at: new Date().toISOString(),
    allowlists: {
      gateway_receipt_signer_dids: [did],
      web_receipt_signer_dids: [],
      attestation_signer_dids: [],
      execution_attestation_signer_dids: [],
      derivation_attestation_signer_dids: [],
      audit_result_attestation_signer_dids: [],
    },
  };
  fs.writeFileSync(path.join(dir, 'config.json'), JSON.stringify(config, null, 2) + '\n');
  log('  ✓ config.json    → verifier config (trusts your DID)');

  // 4. Write README.md
  const readme = `# .clawsig/

Auto-generated by \`clawsig init\`.

## Files

| File | Purpose |
|------|---------|
| \`identity.json\` | Ed25519 key pair (JWK) + derived \`did:key\`. **Keep private.** |
| \`config.json\` | Verifier config that trusts your DID for self-verification. |

## Your DID

\`\`\`
${did}
\`\`\`

## Usage

\`\`\`bash
# Verify a proof bundle using your config
npx @clawbureau/clawverify-cli verify proof-bundle \\
  --input bundle.json \\
  --config .clawsig/config.json
\`\`\`

## Security

- \`identity.json\` contains your private key. Add \`.clawsig/\` to \`.gitignore\`.
- Never commit private keys to version control.
- Rotate keys by running \`clawsig init --force\`.

## Learn more

- Protocol spec: https://clawsig.com
- Adoption guide: https://github.com/clawbureau/clawbureau/blob/main/docs/specs/clawsig-protocol/ADOPTION_GUIDE.md
`;
  fs.writeFileSync(path.join(dir, 'README.md'), readme);
  log('  ✓ README.md      → quick reference');

  // 5. Suggest .gitignore addition
  const gitignorePath = path.resolve(process.cwd(), '.gitignore');
  let addedGitignore = false;
  if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, 'utf8');
    if (!content.includes('.clawsig/')) {
      fs.appendFileSync(gitignorePath, '\n# Clawsig identity (contains private key)\n.clawsig/\n');
      addedGitignore = true;
      log('  ✓ .gitignore     → added .clawsig/ exclusion');
    }
  }

  log(`\n✓ Done.${addedGitignore ? '' : ' Remember to add .clawsig/ to .gitignore.'}\n`);
  log('Next steps:');
  log('  1. Install the SDK:     npm install @clawbureau/clawsig-sdk');
  log('  2. Create a proof run:  import { createClawsigRun } from "@clawbureau/clawsig-sdk"');
  log('  3. Verify bundles:      npx @clawbureau/clawverify-cli verify proof-bundle --input bundle.json --config .clawsig/config.json');
  log(`\nYour agent DID: ${did}`);
}

main().catch((err: unknown) => {
  process.stderr.write(`Error: ${err instanceof Error ? err.message : 'unknown error'}\n`);
  process.exitCode = 1;
});
