// Generated by Wrangler by running `wrangler types src/env.d.ts`

interface Env {
	ENVIRONMENT: "production" | "staging";
	CLAWTRIALS_VERSION: "0.2.0" | "0.2.0-staging";
	CLAWREP_BASE_URL: "https://clawrep.com" | "https://staging.clawrep.com";
	REP_EVENTS: Queue;
}
