// Generated by Wrangler by running `wrangler types src/env.d.ts`

interface Env {
	REP_CACHE: KVNamespace;
	REP_VERSION: "0.1.0";
	REP_DECAY_DAILY_RATE: "0.02";
	REP_REVIEWER_CACHE_TTL_SECONDS: "120";
	REP_DB: D1Database;
	REP_EVENTS: Queue;
}
