// Generated by Wrangler by running `wrangler types src/env.d.ts`

interface Env {
  DELEGATE_DB: D1Database;
  DELEGATION_DO: DurableObjectNamespace;
  DELEGATE_EVENTS?: Queue;
  DELEGATE_CACHE?: KVNamespace;

  ENVIRONMENT?: string;
  DELEGATE_VERSION?: string;

  SCOPE_BASE_URL?: string;
  CLAIM_BASE_URL?: string;
  CONTROLS_BASE_URL?: string;
  LEDGER_BASE_URL?: string;

  DELEGATE_ADMIN_KEY?: string;
  SCOPE_ADMIN_KEY?: string;
  CLAIM_DELEGATE_KEY?: string;
  LEDGER_ADMIN_KEY?: string;

  DELEGATE_SERVICE_DID?: string;
  DELEGATE_SCOPE_OWNER_DID?: string;
  DELEGATE_SCOPE_CONTROLLER_DID?: string;
  DELEGATE_SCOPE_AGENT_DID?: string;
  DELEGATE_SCOPE_TOKEN_TTL_SECONDS?: string;
  DELEGATE_TIMEOUT_MS?: string;
}
