/**
 * Static pillar pages: /trust, /trust/security-review, /secure-workers, /consulting, /about
 * These are hand-crafted high-value pages, not generated by Gemini.
 */

import { layout } from "../layout";
import { faqSchema, serviceSchema, howToSchema } from "../seo";

type StaticFaq = { q: string; a: string };

const TRUST_FAQS: StaticFaq[] = [
  {
    q: "How does Claw EA prove AI agent actions are legitimate?",
    a: "Every model call routes through clawproxy, which signs a gateway receipt with the request hash, response hash, model, provider, and timestamp. These receipts are compiled into proof bundles signed by the agent's DID. Any third party can verify the bundle independently.",
  },
  {
    q: "What is a Proof of Harness?",
    a: "Proof of Harness verifies that an AI agent ran inside a controlled execution environment. Gateway receipts from clawproxy prove that model calls were mediated, policy controls were active, and audit logging was operational during execution.",
  },
  {
    q: "Can proof bundles be tampered with?",
    a: "No. Proof bundles use Ed25519 signatures tied to the agent's DID and include Merkle root hashes over all events. Modifying any event invalidates the chain. Gateway receipts are independently signed by clawproxy.",
  },
];

const SECURE_WORKERS_FAQS: StaticFaq[] = [
  {
    q: "How are secure workers isolated from each other?",
    a: "Each agent runs in its own Cloudflare Sandbox with separate process and filesystem boundaries. Agent state is synchronized to tenant/agent-scoped R2 prefixes, so one agent cannot read another agent's persisted data.",
  },
  {
    q: "Can we restrict where workers send data?",
    a: "Yes. Work Policy Contracts enforce explicit egress allowlists and approval gates. Unauthorized destinations are denied at execution time and reflected in audit evidence.",
  },
  {
    q: "What happens when a worker sleeps or restarts?",
    a: "Runtime state is synced to scoped storage before sleep and restored on wake. Restart events and lifecycle transitions are logged so operations teams can verify continuity.",
  },
];

const CONSULTING_FAQS: StaticFaq[] = [
  {
    q: "Do you help with pilot-to-production rollout?",
    a: "Yes. We can support design, rollout sequencing, policy authoring, and operational readiness from first proof-of-concept through production deployment.",
  },
  {
    q: "Can consulting engagements include compliance mapping?",
    a: "Yes. We map controls and evidence outputs to frameworks such as SOC 2, HIPAA, and GDPR, and help prepare audit-friendly runbooks and artifacts.",
  },
  {
    q: "Can you customize integrations and workflows for our stack?",
    a: "Yes. We can implement scoped skills, policy packs, and workflow templates aligned with your existing identity, ticketing, collaboration, and SIEM systems.",
  },
];

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderFaqAccordion(id: string, faqs: StaticFaq[]): string {
  return `<div class="faq-accordion" data-accordion aria-label="Frequently asked questions">${faqs
    .map((faq, i) => {
      const buttonId = `${id}-trigger-${i}`;
      const panelId = `${id}-panel-${i}`;
      const expanded = i === 0;
      return `<div class="faq-item">
          <h3>
            <button
              type="button"
              class="faq-trigger"
              id="${buttonId}"
              aria-expanded="${expanded ? "true" : "false"}"
              aria-controls="${panelId}"
              data-accordion-trigger
            >${esc(faq.q)}</button>
          </h3>
          <div id="${panelId}" class="faq-panel" role="region" aria-labelledby="${buttonId}" ${expanded ? "" : "hidden"}>
            <p>${esc(faq.a)}</p>
          </div>
        </div>`;
    })
    .join("")}</div>`;
}

export function trustPage(): string {
  return layout({
    meta: {
      title: "Trust Layer | Verified AI Agent Execution | Claw EA",
      description: "Cryptographic proof of every AI agent action. Execution attestation, Proof of Harness, Work Policy Contracts, and tamper-evident audit logs. Trust your AI.",
      path: "/trust",
    },
    breadcrumbs: [{ name: "Home", path: "/" }, { name: "Trust", path: "/trust" }],
    schemas: [
      serviceSchema("Claw EA Trust Layer", "Cryptographic verification infrastructure for enterprise AI agents", "https://www.clawea.com/trust"),
      faqSchema(TRUST_FAQS),
    ],
    body: `
    <section class="hero">
      <div class="wrap">
        <span class="badge badge-green">Trust Infrastructure</span>
        <h1>Every AI Action, Cryptographically Verified</h1>
        <p class="sub">Traditional AI tools ask you to trust them. Claw EA gives you proof. Every model call receipted. Every action attested. Every output verifiable by third parties.</p>
        <div class="actions">
          <a href="/agent-proof-and-attestation" class="cta-btn cta-btn-lg">How Attestation Works</a>
          <a href="/proof/gateway-receipts" class="cta-btn cta-btn-outline cta-btn-lg">Gateway Receipts</a>
        </div>
        <ul class="trust-proof-list" aria-label="Compliance posture">
          <li>SOC 2 control mapping</li>
          <li>HIPAA/GDPR evidence packs</li>
          <li>FedRAMP-ready control posture</li>
        </ul>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="sh"><h2>Three Layers of Trust</h2></div>
        <div class="grid-3">
          <div class="card">
            <div class="icon">🔏</div>
            <h3>Execution Attestation</h3>
            <p>Every model call, tool invocation, and data access generates a signed event. Events are chained into Universal Run Manifests with Merkle integrity.</p>
            <p><a href="/agent-proof-and-attestation">Learn more &rarr;</a></p>
          </div>
          <div class="card">
            <div class="icon">🔐</div>
            <h3>Proof of Harness</h3>
            <p>Gateway receipts from clawproxy prove the agent ran inside a controlled sandbox with active policy enforcement. Not just what it did, but where it ran.</p>
            <p><a href="/proof/proof-bundles">Learn more &rarr;</a></p>
          </div>
          <div class="card">
            <div class="icon">📋</div>
            <h3>Work Policy Contracts</h3>
            <p>Define guardrails before agents run. WPCs enforce egress controls, DLP redaction, model restrictions, and approval gates. Policy hash embedded in every proof bundle.</p>
            <p><a href="/policy/work-policy-contract">Learn more &rarr;</a></p>
          </div>
        </div>
      </div>
    </section>

    <section class="section" style="background:var(--bg-alt)">
      <div class="wrap">
        <div class="feat-row">
          <div>
            <span class="badge badge-blue">How It Works</span>
            <h3>From Agent Action to Proof Bundle</h3>
            <p>Every interaction follows a verifiable chain.</p>
            <ul>
              <li>Agent receives task, creates run context with unique run_id</li>
              <li>Model calls route through clawproxy, producing signed receipts</li>
              <li>Tool invocations generate hashed event records</li>
              <li>All outputs are SHA-256 hashed as artifacts</li>
              <li>Universal Run Manifest compiled and signed by agent DID</li>
              <li>Merkle log root seals the bundle for tamper detection</li>
            </ul>
          </div>
          <div class="feat-visual trust-flow-desktop" role="img" aria-label="Flow: task received, gateway receipt created, tool event hashed, output artifact hashed, then all records sealed into a signed universal run manifest.">
            <div class="trust-flow-chart">
              <div class="trust-flow-step">1. Task assigned and run context created</div>
              <div class="trust-flow-arrow" aria-hidden="true">↓</div>
              <div class="trust-flow-step">2. Model call mediated by clawproxy → signed gateway receipt</div>
              <div class="trust-flow-arrow" aria-hidden="true">↓</div>
              <div class="trust-flow-step">3. Tool invocation recorded as hashed event</div>
              <div class="trust-flow-arrow" aria-hidden="true">↓</div>
              <div class="trust-flow-step">4. Output artifacts hashed and attached to run</div>
              <div class="trust-flow-arrow" aria-hidden="true">↓</div>
              <div class="trust-flow-step">5. Universal Run Manifest sealed with Merkle root + agent DID signature</div>
            </div>
          </div>
          <ol class="trust-flow-mobile" aria-label="Proof flow summary">
            <li>Task assigned and run context created.</li>
            <li>Model call mediated by clawproxy with a signed gateway receipt.</li>
            <li>Tool invocation recorded as a hashed event.</li>
            <li>Output artifacts hashed and attached to the run record.</li>
            <li>Universal Run Manifest sealed with Merkle root and agent DID signature.</li>
          </ol>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="sh"><h2>Frequently Asked Questions</h2></div>
        ${renderFaqAccordion("trust-faq", TRUST_FAQS)}
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="cta-banner">
          <h2>See Trust Infrastructure in Action</h2>
          <p>Review our architecture, threat model, and real proof artifacts. Everything your security team needs.</p>
          <a href="/trust/security-review" class="cta-btn cta-btn-lg" data-cta="trust-security-review">Security Review Pack</a>
          <a href="/book" class="cta-btn cta-btn-outline cta-btn-lg" style="margin-left:.75rem" data-cta="trust-book">Book rollout session</a>
        </div>
      </div>
    </section>`,
  });
}

/* ── Security Review Pack ──────────────────────────────────────── */

const SECURITY_REVIEW_FAQS: StaticFaq[] = [
  {
    q: "Can we verify proof bundles without calling your API?",
    a: "Yes. Proof bundles use Ed25519 signatures and SHA-256 hashes. Any team with the agent's public DID key and the clawproxy gateway public key can verify bundles offline using standard cryptographic libraries. No network call required.",
  },
  {
    q: "What happens if clawproxy is unavailable during a run?",
    a: "The agent cannot make model calls. clawproxy is not optional middleware; it is the only path to LLM providers. If clawproxy is down, execution halts. This is fail-closed by design.",
  },
  {
    q: "How do you handle nondeterministic model outputs in audit?",
    a: "We do not attempt bit-identical replay. Verification targets policy compliance, receipt binding integrity, and artifact reproducibility (tests/builds). Model nondeterminism is expected; tamper-evidence and receipt chains prove what actually happened.",
  },
  {
    q: "Can agents exfiltrate data through side channels?",
    a: "Agents run in hardware-isolated Cloudflare Sandboxes with strict egress allowlists. All model traffic routes through clawproxy. DNS, UDP, and unauthorized HTTP are blocked at the infrastructure level. DLP redaction strips sensitive data before it leaves the boundary.",
  },
];

export function securityReviewPackPage(): string {
  return layout({
    meta: {
      title: "Security Review Pack | Claw EA Enterprise AI Agents",
      description: "Architecture, threat model, proof artifacts, and deployment integrity for your security team. Everything you need to clear infosec review for enterprise AI agents.",
      path: "/trust/security-review",
    },
    breadcrumbs: [
      { name: "Home", path: "/" },
      { name: "Trust", path: "/trust" },
      { name: "Security Review Pack", path: "/trust/security-review" },
    ],
    schemas: [
      serviceSchema(
        "Claw EA Security Review Pack",
        "Pre-built security review documentation for enterprise AI agent deployments, including architecture, threat model, proof artifacts, and deployment integrity.",
        "https://www.clawea.com/trust/security-review",
      ),
      faqSchema(SECURITY_REVIEW_FAQS),
      howToSchema(
        {
          title: "How to verify a Claw EA proof bundle",
          steps: [
            { name: "Obtain the proof bundle JSON", text: "Export the proof bundle from the agent run. The bundle is a self-contained JSON envelope." },
            { name: "Check the event chain integrity", text: "Recompute each event_hash_b64u from the canonical header fields using SHA-256. Verify prev_hash linkage." },
            { name: "Verify gateway receipts", text: "For each receipt, verify the Ed25519 signature using the clawproxy gateway public key. Confirm receipt binding matches the event chain." },
            { name: "Verify the bundle envelope signature", text: "Verify the outer Ed25519 signature using the agent DID public key. Confirm signer_did matches payload.agent_did." },
            { name: "Check the Merkle root (optional)", text: "If the bundle references a clawlogs Merkle root, request the inclusion proof and verify it against the signed root." },
          ],
        },
        "https://www.clawea.com/trust/security-review",
      ),
    ],
    body: `
    <section class="hero">
      <div class="wrap">
        <span class="badge badge-green">For Security Teams</span>
        <h1>Security Review Pack</h1>
        <p class="sub">Everything your infosec team needs to evaluate Claw EA. Architecture, threat model, real proof artifacts, and deployment integrity. No fluff, no marketing claims. Just evidence.</p>
        <div class="actions">
          <a href="/book" class="cta-btn cta-btn-lg" data-cta="security-review-book">Book a rollout session</a>
          <button type="button" class="cta-btn cta-btn-outline cta-btn-lg" data-cta="security-review-print" onclick="window.print()">Download this pack</button>
        </div>
      </div>
    </section>

    <nav class="section-sm" style="border-bottom:1px solid var(--border)">
      <div class="wrap">
        <div class="toc" role="navigation" aria-label="Page contents">
          <a href="#architecture">Architecture</a>
          <a href="#proof-bundle">Proof Bundle</a>
          <a href="#commit-proof">Commit Proof</a>
          <a href="#threat-model">Threat Model</a>
          <a href="#tamper-evidence">Tamper Evidence</a>
          <a href="#deployment-integrity">Deployment Integrity</a>
        </div>
      </div>
    </nav>

    <section class="section" id="architecture">
      <div class="wrap" style="max-width:900px">
        <div class="sh"><h2>Architecture and Data Flow</h2></div>
        <p>Every AI agent action follows a single verifiable path. No model call bypasses the gateway. No side effect occurs without a hashed event record.</p>

        <div class="trust-flow-chart" style="margin:2rem 0" role="img" aria-label="Data flow: agent receives task, model call routes through clawproxy which signs a gateway receipt, tool invocations produce hashed events, outputs are SHA-256 hashed as artifacts, all records compile into a signed proof bundle, and the bundle root is anchored to the clawlogs Merkle transparency log.">
          <div class="trust-flow-step"><strong>1. Task assigned</strong> &mdash; Agent receives task, creates run context with unique run_id</div>
          <div class="trust-flow-arrow" aria-hidden="true">&darr;</div>
          <div class="trust-flow-step"><strong>2. Model call mediated</strong> &mdash; LLM request routes through <a href="/proof/gateway-receipts">clawproxy</a> &rarr; signed gateway receipt (Ed25519)</div>
          <div class="trust-flow-arrow" aria-hidden="true">&darr;</div>
          <div class="trust-flow-step"><strong>3. Tool invocation recorded</strong> &mdash; Each tool call produces a hashed event with SHA-256 payload hash and prev_hash linkage</div>
          <div class="trust-flow-arrow" aria-hidden="true">&darr;</div>
          <div class="trust-flow-step"><strong>4. Outputs hashed</strong> &mdash; Every output artifact is SHA-256 hashed and attached to the Universal Run Manifest</div>
          <div class="trust-flow-arrow" aria-hidden="true">&darr;</div>
          <div class="trust-flow-step"><strong>5. Proof bundle sealed</strong> &mdash; Event chain + receipts + URM compiled and signed by agent DID (Ed25519)</div>
          <div class="trust-flow-arrow" aria-hidden="true">&darr;</div>
          <div class="trust-flow-step"><strong>6. Merkle anchor</strong> &mdash; Bundle root submitted to <a href="/audit/tamper-evident-logs">clawlogs</a> transparency log with signed inclusion proof</div>
        </div>

        <div class="grid-3" style="margin-top:1.5rem">
          <div class="card">
            <h3>Fail-closed gateway</h3>
            <p>clawproxy is the only path to LLM providers. If the gateway is down, the agent cannot make model calls. No bypass, no fallback.</p>
          </div>
          <div class="card">
            <h3>Hardware isolation</h3>
            <p>Each agent runs in its own <a href="/secure-workers">Cloudflare Sandbox</a> with per-agent DID identity, scoped storage, and strict egress controls.</p>
          </div>
          <div class="card">
            <h3>Policy-as-code</h3>
            <p><a href="/policy/work-policy-contract">Work Policy Contracts</a> define egress allowlists, DLP rules, approval gates, and model restrictions before any agent runs.</p>
          </div>
        </div>
      </div>
    </section>

    <section class="section" id="proof-bundle" style="background:var(--bg-alt)">
      <div class="wrap" style="max-width:900px">
        <div class="sh"><h2>Proof Bundle: Real Artifact</h2></div>
        <p>Below is a proof bundle from our conformance test suite. This is the exact JSON structure your auditors will inspect. DID values are from test fixtures; production bundles use per-agent and per-gateway keys.</p>

        <pre aria-label="Proof bundle JSON structure"><code>{
  "envelope_version": "1",
  "envelope_type": "proof_bundle",
  "payload": {
    "bundle_version": "1",
    "bundle_id": "bundle_conformance_001",
    "agent_did": "did:key:z6Mkn...E7c7",
    "event_chain": [
      {
        "event_id": "evt_conformance_001",
        "run_id": "run_conformance_001",
        "event_type": "llm_call",
        "timestamp": "2026-02-12T00:00:00.000Z",
        "payload_hash_b64u": "ibhRTWt5...fCEu8",
        "prev_hash_b64u": null,
        "event_hash_b64u": "mo72_ab1...5-Jds"
      }
    ],
    "receipts": [
      {
        "envelope_version": "1",
        "envelope_type": "gateway_receipt",
        "payload": {
          "receipt_version": "1",
          "receipt_id": "rcpt_conformance_001",
          "gateway_id": "gw_conformance",
          "provider": "anthropic",
          "model": "claude-sonnet-4-20250514",
          "request_hash_b64u": "znFMvVUo...daXI",
          "response_hash_b64u": "I-UgWdP2...ylBY",
          "tokens_input": 10,
          "tokens_output": 20,
          "latency_ms": 123,
          "binding": {
            "run_id": "run_conformance_001",
            "event_hash_b64u": "mo72_ab1...5-Jds",
            "nonce": "nonce_conformance_001"
          }
        },
        "signature_b64u": "q7q0bn1b...5MAA",
        "algorithm": "Ed25519",
        "signer_did": "did:key:z6Mkf...xy3m"
      }
    ]
  },
  "payload_hash_b64u": "HZYtCYB_...7Lyk",
  "hash_algorithm": "SHA-256",
  "signature_b64u": "9FS8CmJ7...5ZDw",
  "algorithm": "Ed25519",
  "signer_did": "did:key:z6Mkn...E7c7",
  "issued_at": "2026-02-12T00:00:02.000Z"
}</code></pre>

        <div class="grid-2" style="margin-top:1.5rem">
          <div class="card">
            <h3>What this proves</h3>
            <ul>
              <li>The agent with DID <code>z6Mkn...E7c7</code> executed a run</li>
              <li>One LLM call was mediated by clawproxy (gateway receipt signed by <code>z6Mkf...xy3m</code>)</li>
              <li>The receipt is cryptographically bound to the event via <code>event_hash_b64u</code> and <code>run_id</code></li>
              <li>The entire bundle is signed by the agent's Ed25519 key</li>
              <li>Any modification to any field invalidates the signature chain</li>
            </ul>
          </div>
          <div class="card">
            <h3>How to verify</h3>
            <ul>
              <li>Decode <code>signer_did</code> to extract the Ed25519 public key</li>
              <li>Verify <code>signature_b64u</code> over <code>payload_hash_b64u</code></li>
              <li>Recompute <code>payload_hash_b64u</code> from the canonical JSON payload</li>
              <li>Verify each receipt signature independently</li>
              <li>Confirm receipt <code>binding.event_hash_b64u</code> exists in the event chain</li>
            </ul>
            <p style="margin-top:.75rem"><a href="/proof/proof-bundles">Full verification guide &rarr;</a></p>
          </div>
        </div>
      </div>
    </section>

    <section class="section" id="commit-proof">
      <div class="wrap" style="max-width:900px">
        <div class="sh"><h2>Commit Proof: Deployment Signature</h2></div>
        <p>Every code change in the Claw Bureau repo carries a DID-signed commit proof. This is a real <code>commit.sig.json</code> from our own repository.</p>

        <pre aria-label="Commit signature JSON structure"><code>{
  "version": "m1",
  "type": "message_signature",
  "algo": "ed25519",
  "did": "did:key:z6Mkt...m8XW",
  "message": "commit:3d95fe55...42c269",
  "createdAt": "2026-02-12T12:21:40.739Z",
  "signature": "I0AhFPwQ...ipoDg=="
}</code></pre>

        <p>To verify: decode the <code>did:key</code> to extract the Ed25519 public key, then verify <code>signature</code> over the UTF-8 bytes of <code>message</code>. The <code>message</code> field references the exact git commit SHA. If any byte of the commit changes, the signature fails.</p>
        <p>We run this on every agent-generated PR through our <a href="/workflows/production-deploy-approval">Claw Verified PR pipeline</a>. The GitHub check enforces that proof artifacts are present and valid before merge.</p>
      </div>
    </section>

    <section class="section" id="threat-model" style="background:var(--bg-alt)">
      <div class="wrap" style="max-width:900px">
        <div class="sh"><h2>Threat Model</h2></div>
        <p>We commissioned adversarial red-team analysis against our Proof of Harness primitives. Here are the four primary threat categories and how our architecture addresses each.</p>

        <div class="grid-2">
          <div class="card">
            <h3>Replay and evidence reuse</h3>
            <p><strong>Threat:</strong> An agent reuses receipts or event chains from a previous run to fake evidence of new work.</p>
            <p><strong>Mitigations:</strong></p>
            <ul>
              <li>Each run uses a unique <code>run_id</code> bound into every receipt and event</li>
              <li>Receipt nonces prevent duplicate submission</li>
              <li>Job-scoped tokens (<code>token_scope_hash</code>) tie receipts to specific assignments</li>
              <li>Server-side replay detection rejects previously-seen receipt IDs</li>
            </ul>
          </div>
          <div class="card">
            <h3>Data exfiltration</h3>
            <p><strong>Threat:</strong> An agent sends sensitive enterprise data to unauthorized endpoints via HTTP, DNS tunneling, or side channels.</p>
            <p><strong>Mitigations:</strong></p>
            <ul>
              <li>Hardware-isolated Cloudflare Sandboxes with strict egress allowlists</li>
              <li>All model traffic routes exclusively through clawproxy</li>
              <li>DNS and UDP blocked at the infrastructure level</li>
              <li>DLP redaction pipeline strips PII/PHI before data leaves the boundary</li>
              <li>Unauthorized egress attempts logged and surfaced in proof bundles</li>
            </ul>
          </div>
          <div class="card">
            <h3>Prompt injection</h3>
            <p><strong>Threat:</strong> Malicious input (repository content, user messages, file contents) manipulates the agent into performing unauthorized actions.</p>
            <p><strong>Mitigations:</strong></p>
            <ul>
              <li>Split context architecture: identity root (seller instructions) separated from job root (buyer content)</li>
              <li>Untrusted content wrapped in XML boundary tags</li>
              <li>Tool restrictions enforced by Work Policy Contracts, not by the model</li>
              <li>Approval gates require human confirmation for irreversible actions</li>
              <li>All tool invocations are logged regardless of prompt context</li>
            </ul>
          </div>
          <div class="card">
            <h3>Nondeterminism and audit integrity</h3>
            <p><strong>Threat:</strong> LLM outputs are inherently nondeterministic, making bit-identical replay impossible and raising questions about audit reliability.</p>
            <p><strong>Mitigations:</strong></p>
            <ul>
              <li>Verification targets policy compliance and receipt integrity, not token-identical reproduction</li>
              <li>Gateway receipts prove which model was called, what was sent, and what was received (via hashes)</li>
              <li>Artifact-level reproducibility (tests, builds) provides objective outcome verification</li>
              <li>Timestamp monotonicity enforced across event chains</li>
              <li>Evidence re-validation is the core "replay" primitive, not re-execution</li>
            </ul>
          </div>
        </div>

        <p style="margin-top:1.5rem">Full red-team analysis covers 25+ specific attack vectors including event chain fabrication, receipt binding manipulation, attestation forgery, policy hash confusion, and resource exhaustion. <a href="/contact" data-cta="security-review-threat-details">Request the full threat model document</a>.</p>
      </div>
    </section>

    <section class="section" id="tamper-evidence">
      <div class="wrap" style="max-width:900px">
        <div class="sh"><h2>Tamper-Evident Logging</h2></div>
        <p>All proof bundles are anchored to the <a href="/audit/tamper-evident-logs">clawlogs Merkle transparency log</a>. This is an append-only data structure where any modification to historical entries is cryptographically detectable.</p>

        <div class="grid-2">
          <div class="card">
            <h3>Merkle construction</h3>
            <ul>
              <li>Leaf hashes are base64url-encoded SHA-256 digests</li>
              <li>Parent nodes: <code>SHA-256(left || right)</code></li>
              <li>Odd-node rule: duplicate last node</li>
              <li>Root signed by clawlogs Ed25519 key (<code>did:key</code>)</li>
            </ul>
          </div>
          <div class="card">
            <h3>Inclusion proof verification</h3>
            <ul>
              <li>Request inclusion proof for any leaf hash via <code>GET /proof/:leaf_hash_b64u</code></li>
              <li>Verify <code>audit_path[]</code> from leaf sibling upward to root</li>
              <li>Confirm computed root matches the signed <code>root_hash_b64u</code></li>
              <li>Verify root signature using clawlogs public key</li>
              <li>If signature verification fails, the entire check fails closed</li>
            </ul>
          </div>
        </div>

        <p style="margin-top:1rem">Retention: all log entries are retained indefinitely. Inclusion proofs are available for any historical entry. The log is queryable by external auditors without requiring platform access.</p>
      </div>
    </section>

    <section class="section" id="deployment-integrity" style="background:var(--bg-alt)">
      <div class="wrap" style="max-width:900px">
        <div class="sh"><h2>Deployment Integrity</h2></div>
        <p>Every change to the Claw Bureau codebase follows a verified chain from code to production.</p>

        <div class="grid-2">
          <div class="card">
            <h3>Signed commits + DID proofs</h3>
            <ul>
              <li>Every agent-generated PR includes a <code>commit.sig.json</code> proof</li>
              <li>Ed25519 signature over the exact git commit SHA</li>
              <li>Offline-verifiable: no API call needed to confirm authorship</li>
              <li>Proof artifacts stored in <code>proofs/&lt;branch&gt;/commit.sig.json</code></li>
            </ul>
          </div>
          <div class="card">
            <h3>Claw Verified PR pipeline</h3>
            <ul>
              <li>GitHub Actions check runs on every PR</li>
              <li>Validates commit proof signature against declared DID</li>
              <li>Validates proof bundle artifacts (if present) with URM cross-checks</li>
              <li>Enforced on PRs labeled <code>claw-verified</code> or containing proof artifacts</li>
              <li>Observe-by-default; enforce on labeled PRs</li>
            </ul>
          </div>
        </div>

        <p style="margin-top:1rem">This is not a planned feature. It runs on our own repository today. The PR that shipped this page was verified by the same pipeline.</p>
      </div>
    </section>

    <section class="section">
      <div class="wrap" style="max-width:900px">
        <div class="sh"><h2>Frequently Asked Questions</h2></div>
        ${renderFaqAccordion("security-review-faq", SECURITY_REVIEW_FAQS)}
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="cta-banner">
          <h2>Ready to Start Security Review?</h2>
          <p>Book a rollout session and we will walk your security team through the architecture, threat model, and proof verification process.</p>
          <a href="/book" class="cta-btn cta-btn-lg" data-cta="security-review-bottom-book">Book rollout session</a>
          <button type="button" class="cta-btn cta-btn-outline cta-btn-lg" style="margin-left:.75rem" data-cta="security-review-bottom-print" onclick="window.print()">Print this pack</button>
        </div>
      </div>
    </section>`,
  });
}

export function secureWorkersPage(): string {
  return layout({
    meta: {
      title: "Secure AI Workers | Sandboxed Enterprise Agents | Claw EA",
      description: "Every AI agent runs in its own hardware-isolated Cloudflare Sandbox. No shared memory. Strict egress controls. Per-agent DID identity. Enterprise-grade isolation.",
      path: "/secure-workers",
    },
    breadcrumbs: [{ name: "Home", path: "/" }, { name: "Secure Workers", path: "/secure-workers" }],
    schemas: [
      serviceSchema("Secure AI Workers", "Hardware-isolated enterprise AI workers with policy-enforced execution", "https://www.clawea.com/secure-workers"),
      faqSchema(SECURE_WORKERS_FAQS),
    ],
    body: `
    <section class="hero">
      <div class="wrap">
        <span class="badge badge-green">Infrastructure</span>
        <h1>Secure AI Workers for Enterprise</h1>
        <p class="sub">Every agent gets its own Cloudflare Sandbox. Hardware-level isolation. Per-agent cryptographic identity. Strict network egress controls. No shared state between agents.</p>
        <div class="actions">
          <a href="/contact" class="cta-btn cta-btn-lg">Deploy Secure Workers</a>
          <a href="/secure-agent-execution" class="cta-btn cta-btn-outline cta-btn-lg">Architecture Details</a>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="sh"><h2>Security Architecture</h2></div>
        <div class="grid-2">
          <div class="card">
            <div class="icon">🏗️</div>
            <h3>Hardware-Isolated Sandboxes</h3>
            <p>Cloudflare Sandbox provides stronger isolation than containers. Each agent gets its own execution environment with no shared kernel state. This is not Docker on a shared host.</p>
          </div>
          <div class="card">
            <div class="icon">🔒</div>
            <h3>Per-Agent DID Identity</h3>
            <p>Each agent receives a unique Ed25519 Decentralized Identifier at provisioning. All signing operations use this identity. Agents cannot impersonate other agents.</p>
          </div>
          <div class="card">
            <div class="icon">🌐</div>
            <h3>Egress Mediation</h3>
            <p>Work Policy Contracts define exactly which external endpoints each agent can reach. All model calls route through clawproxy. Unauthorized network access is blocked and logged.</p>
          </div>
          <div class="card">
            <div class="icon">📦</div>
            <h3>Scoped R2 Storage</h3>
            <p>Agent state persists in R2 with tenant/agent-scoped prefixes. Agents can only access their own storage subtree. Cross-agent data access is impossible at the infrastructure level.</p>
          </div>
          <div class="card">
            <div class="icon">🔄</div>
            <h3>Sleep/Wake Lifecycle</h3>
            <p>Agents sleep after configurable idle time (default 30 min) and wake on demand. State persists through R2 sync. Pay only for active compute. No data loss during transitions.</p>
          </div>
          <div class="card">
            <div class="icon">🛡️</div>
            <h3>DLP Redaction Pipeline</h3>
            <p>Built-in data loss prevention strips sensitive data (PII, PHI, financial data) before it leaves the sandbox. Redaction actions are logged in the proof bundle.</p>
          </div>
        </div>
      </div>
    </section>

    <section class="section" style="background:var(--bg-alt)">
      <div class="wrap">
        <div class="stats">
          <div class="stat"><div class="num">100</div><div class="label">Concurrent containers (expandable)</div></div>
          <div class="stat"><div class="num">Zero</div><div class="label">Cross-tenant leakage</div></div>
          <div class="stat"><div class="num">Ed25519</div><div class="label">Per-agent identity</div></div>
          <div class="stat"><div class="num">5 min</div><div class="label">Health check interval</div></div>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="sh"><h2>Frequently Asked Questions</h2></div>
        ${renderFaqAccordion("secure-workers-faq", SECURE_WORKERS_FAQS)}
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="cta-banner">
          <h2>Deploy Secure AI Workers Today</h2>
          <p>Hardware-isolated, policy-enforced, cryptographically attested.</p>
          <a href="/contact" class="cta-btn cta-btn-lg">Talk to Sales</a>
          <a href="/guides/first-30-days" class="cta-btn cta-btn-outline cta-btn-lg" style="margin-left:.75rem">Deployment Guide</a>
        </div>
      </div>
    </section>`,
  });
}

export function consultingPage(): string {
  return layout({
    meta: {
      title: "Enterprise AI Consulting | Agent Strategy & Deployment | Claw EA",
      description: "Expert consulting for enterprise AI agent strategy, deployment, and operations. From proof of concept to production fleet. Custom agent configurations and compliance mapping.",
      path: "/consulting",
    },
    breadcrumbs: [{ name: "Home", path: "/" }, { name: "Consulting", path: "/consulting" }],
    schemas: [
      serviceSchema("Enterprise AI Consulting", "Consulting services for enterprise AI agent strategy, deployment, and operations", "https://www.clawea.com/consulting"),
      faqSchema(CONSULTING_FAQS),
    ],
    body: `
    <section class="hero">
      <div class="wrap">
        <span class="badge badge-purple">Professional Services</span>
        <h1>Enterprise AI Agent Consulting</h1>
        <p class="sub">From strategy to production. Our team helps enterprises design, deploy, and operate AI agent fleets that meet compliance requirements and deliver measurable ROI.</p>
        <div class="actions">
          <a href="/contact" class="cta-btn cta-btn-lg">Book a Consultation</a>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="grid-3">
          <div class="card">
            <div class="icon">🧭</div>
            <h3>AI Agent Strategy</h3>
            <p>Identify the highest-ROI use cases for your industry. Map agent capabilities to business processes. Design the deployment roadmap.</p>
          </div>
          <div class="card">
            <div class="icon">🚀</div>
            <h3>Deployment Services</h3>
            <p>Custom agent templates. Work Policy Contract design. Model routing configuration. Channel integration setup. We get your first fleet running in days, not months.</p>
          </div>
          <div class="card">
            <div class="icon">📊</div>
            <h3>Compliance Mapping</h3>
            <p>Map Claw EA controls to your regulatory framework (SOC 2, HIPAA, GDPR, FedRAMP, PCI DSS). Pre-audit documentation. Auditor briefing support.</p>
          </div>
          <div class="card">
            <div class="icon">🔧</div>
            <h3>Custom Development</h3>
            <p>Custom OpenClaw skills for your workflows. Bespoke agent templates. SIEM and GRC integrations. API integrations with your existing tools.</p>
          </div>
          <div class="card">
            <div class="icon">📈</div>
            <h3>Optimization</h3>
            <p>Model routing optimization to reduce costs 40-60%. Agent fleet right-sizing. Performance tuning. Budget control configuration.</p>
          </div>
          <div class="card">
            <div class="icon">🎓</div>
            <h3>Training</h3>
            <p>Train your team on agent management, WPC design, proof bundle verification, and fleet operations. Role-based training for admins, developers, and compliance officers.</p>
          </div>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="sh"><h2>Frequently Asked Questions</h2></div>
        ${renderFaqAccordion("consulting-faq", CONSULTING_FAQS)}
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="cta-banner">
          <h2>Start With a Free Assessment</h2>
          <p>30-minute call to identify your top AI agent use cases and compliance requirements.</p>
          <a href="/contact" class="cta-btn cta-btn-lg">Book a Consultation</a>
        </div>
      </div>
    </section>`,
  });
}

export function aboutPage(): string {
  return layout({
    meta: {
      title: "About Claw Bureau | Enterprise AI Trust Infrastructure",
      description: "Claw Bureau builds trust infrastructure for the AI agent economy. Verified execution, cryptographic attestation, and enterprise-grade security.",
      path: "/about",
    },
    breadcrumbs: [{ name: "Home", path: "/" }, { name: "About", path: "/about" }],
    body: `
    <section class="section content-page">
      <div class="wrap">
        <h1>Building Trust Infrastructure for AI Agents</h1>
        <p class="lead">Claw Bureau exists because the world is deploying AI agents without the infrastructure to verify what those agents actually do. We are changing that.</p>

        <h2>The Problem</h2>
        <p>Enterprises are deploying AI agents into production workflows. These agents access sensitive data, make decisions, and interact with customers. But there is no way to prove what an agent did, where it ran, or whether policy controls were active during execution.</p>
        <p>Traditional logging is mutable. Traditional security is perimeter-based. Neither works for autonomous AI agents that operate across models, channels, and data sources.</p>

        <h2>Our Approach</h2>
        <p>Claw Bureau builds cryptographic verification infrastructure for AI agent operations. Every agent action produces a signed, tamper-evident record. Proof bundles can be independently verified by auditors, regulators, or counterparties without trusting the platform operator.</p>

        <h2>The Ecosystem</h2>
        <p>Claw EA is part of the broader Claw Bureau ecosystem:</p>
        <ul>
          <li><strong><a href="https://clawverify.com">clawverify.com</a></strong> - Signature verification API</li>
          <li><strong><a href="https://clawproxy.com">clawproxy.com</a></strong> - Gateway receipts and Proof of Harness</li>
          <li><strong><a href="https://clawbounties.com">clawbounties.com</a></strong> - AI agent bounty marketplace</li>
          <li><strong><a href="https://clawescrow.com">clawescrow.com</a></strong> - Payment escrow for agent work</li>
          <li><strong><a href="https://clawcuts.com">clawcuts.com</a></strong> - Revenue sharing infrastructure</li>
          <li><strong><a href="https://clawbureau.com">clawbureau.com</a></strong> - Ecosystem hub</li>
        </ul>

        <h2>Built on OpenClaw</h2>
        <p>Claw EA deploys managed OpenClaw instances. OpenClaw is a personal AI assistant platform with 20+ channel integrations, multi-model support, plugin architecture, and hybrid memory search. We add the enterprise trust layer: sandboxed execution, Work Policy Contracts, cryptographic attestation, and fleet management.</p>
      </div>
    </section>`,
  });
}
