/**
 * Static pillar pages: /trust, /secure-workers, /consulting, /about
 * These are hand-crafted high-value pages, not generated by Gemini.
 */

import { layout } from "../layout";
import { faqSchema, serviceSchema } from "../seo";

export function trustPage(): string {
  return layout({
    meta: {
      title: "Trust Layer | Verified AI Agent Execution | Claw EA",
      description: "Cryptographic proof of every AI agent action. Execution attestation, Proof of Harness, Work Policy Contracts, and tamper-evident audit logs. Trust your AI.",
      path: "/trust",
    },
    breadcrumbs: [{ name: "Home", path: "/" }, { name: "Trust", path: "/trust" }],
    schemas: [
      serviceSchema("Claw EA Trust Layer", "Cryptographic verification infrastructure for enterprise AI agents", "https://www.clawea.com/trust"),
      faqSchema([
        { q: "How does Claw EA prove AI agent actions are legitimate?", a: "Every model call routes through clawproxy, which signs a gateway receipt with the request hash, response hash, model, provider, and timestamp. These receipts are compiled into proof bundles signed by the agent's DID. Any third party can verify the bundle independently." },
        { q: "What is a Proof of Harness?", a: "Proof of Harness verifies that an AI agent ran inside a controlled execution environment. Gateway receipts from clawproxy prove that model calls were mediated, policy controls were active, and audit logging was operational during execution." },
        { q: "Can proof bundles be tampered with?", a: "No. Proof bundles use Ed25519 signatures tied to the agent's DID and include Merkle root hashes over all events. Modifying any event invalidates the chain. Gateway receipts are independently signed by clawproxy." },
      ]),
    ],
    body: `
    <section class="hero">
      <div class="wrap">
        <span class="badge badge-green">Trust Infrastructure</span>
        <h1>Every AI Action, Cryptographically Verified</h1>
        <p class="sub">Traditional AI tools ask you to trust them. Claw EA gives you proof. Every model call receipted. Every action attested. Every output verifiable by third parties.</p>
        <div class="actions">
          <a href="/agent-proof-and-attestation" class="cta-btn cta-btn-lg">How Attestation Works</a>
          <a href="/proof/gateway-receipts" class="cta-btn cta-btn-outline cta-btn-lg">Gateway Receipts</a>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="sh"><h2>Three Layers of Trust</h2></div>
        <div class="grid-3">
          <div class="card">
            <div class="icon">🔏</div>
            <h3>Execution Attestation</h3>
            <p>Every model call, tool invocation, and data access generates a signed event. Events are chained into Universal Run Manifests with Merkle integrity.</p>
            <p><a href="/agent-proof-and-attestation">Learn more &rarr;</a></p>
          </div>
          <div class="card">
            <div class="icon">🔐</div>
            <h3>Proof of Harness</h3>
            <p>Gateway receipts from clawproxy prove the agent ran inside a controlled sandbox with active policy enforcement. Not just what it did, but where it ran.</p>
            <p><a href="/proof/proof-bundles">Learn more &rarr;</a></p>
          </div>
          <div class="card">
            <div class="icon">📋</div>
            <h3>Work Policy Contracts</h3>
            <p>Define guardrails before agents run. WPCs enforce egress controls, DLP redaction, model restrictions, and approval gates. Policy hash embedded in every proof bundle.</p>
            <p><a href="/policy/work-policy-contract">Learn more &rarr;</a></p>
          </div>
        </div>
      </div>
    </section>

    <section class="section" style="background:var(--bg-alt)">
      <div class="wrap">
        <div class="feat-row">
          <div>
            <span class="badge badge-blue">How It Works</span>
            <h3>From Agent Action to Proof Bundle</h3>
            <p>Every interaction follows a verifiable chain.</p>
            <ul>
              <li>Agent receives task, creates run context with unique run_id</li>
              <li>Model calls route through clawproxy, producing signed receipts</li>
              <li>Tool invocations generate hashed event records</li>
              <li>All outputs are SHA-256 hashed as artifacts</li>
              <li>Universal Run Manifest compiled and signed by agent DID</li>
              <li>Merkle log root seals the bundle for tamper detection</li>
            </ul>
          </div>
          <div class="feat-visual">
Task Assigned
  |
  v
[clawproxy] --> receipt_001 (signed)
  |
  v
[tool: read_file] --> event_002 (hashed)
  |
  v
[clawproxy] --> receipt_003 (signed)
  |
  v
[output] --> artifact_hash_004
  |
  v
Universal Run Manifest
  + receipts[]
  + events[]
  + artifacts[]
  + merkle_root
  + agent_signature (Ed25519)</div>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap faq">
        <div class="sh"><h2>Frequently Asked Questions</h2></div>
        <div class="faq-item">
          <h3>How does Claw EA prove AI agent actions are legitimate?</h3>
          <p>Every model call routes through clawproxy, which signs a gateway receipt with the request hash, response hash, model, provider, and timestamp. These receipts are compiled into proof bundles signed by the agent's DID. Any third party can verify the bundle independently.</p>
        </div>
        <div class="faq-item">
          <h3>What is a Proof of Harness?</h3>
          <p>Proof of Harness verifies that an AI agent ran inside a controlled execution environment. Gateway receipts from clawproxy prove that model calls were mediated, policy controls were active, and audit logging was operational during execution.</p>
        </div>
        <div class="faq-item">
          <h3>Can proof bundles be tampered with?</h3>
          <p>No. Proof bundles use Ed25519 signatures tied to the agent's DID and include Merkle root hashes over all events. Modifying any event invalidates the chain. Gateway receipts are independently signed by clawproxy.</p>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="cta-banner">
          <h2>See Trust Infrastructure in Action</h2>
          <p>Deploy a verified agent and inspect the proof bundle yourself.</p>
          <a href="/contact" class="cta-btn cta-btn-lg">Request a Demo</a>
        </div>
      </div>
    </section>`,
  });
}

export function secureWorkersPage(): string {
  return layout({
    meta: {
      title: "Secure AI Workers | Sandboxed Enterprise Agents | Claw EA",
      description: "Every AI agent runs in its own hardware-isolated Cloudflare Sandbox. No shared memory. Strict egress controls. Per-agent DID identity. Enterprise-grade isolation.",
      path: "/secure-workers",
    },
    breadcrumbs: [{ name: "Home", path: "/" }, { name: "Secure Workers", path: "/secure-workers" }],
    body: `
    <section class="hero">
      <div class="wrap">
        <span class="badge badge-green">Infrastructure</span>
        <h1>Secure AI Workers for Enterprise</h1>
        <p class="sub">Every agent gets its own Cloudflare Sandbox. Hardware-level isolation. Per-agent cryptographic identity. Strict network egress controls. No shared state between agents.</p>
        <div class="actions">
          <a href="/contact" class="cta-btn cta-btn-lg">Deploy Secure Workers</a>
          <a href="/secure-agent-execution" class="cta-btn cta-btn-outline cta-btn-lg">Architecture Details</a>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="sh"><h2>Security Architecture</h2></div>
        <div class="grid-2">
          <div class="card">
            <div class="icon">🏗️</div>
            <h3>Hardware-Isolated Sandboxes</h3>
            <p>Cloudflare Sandbox provides stronger isolation than containers. Each agent gets its own execution environment with no shared kernel state. This is not Docker on a shared host.</p>
          </div>
          <div class="card">
            <div class="icon">🔒</div>
            <h3>Per-Agent DID Identity</h3>
            <p>Each agent receives a unique Ed25519 Decentralized Identifier at provisioning. All signing operations use this identity. Agents cannot impersonate other agents.</p>
          </div>
          <div class="card">
            <div class="icon">🌐</div>
            <h3>Egress Mediation</h3>
            <p>Work Policy Contracts define exactly which external endpoints each agent can reach. All model calls route through clawproxy. Unauthorized network access is blocked and logged.</p>
          </div>
          <div class="card">
            <div class="icon">📦</div>
            <h3>Scoped R2 Storage</h3>
            <p>Agent state persists in R2 with tenant/agent-scoped prefixes. Agents can only access their own storage subtree. Cross-agent data access is impossible at the infrastructure level.</p>
          </div>
          <div class="card">
            <div class="icon">🔄</div>
            <h3>Sleep/Wake Lifecycle</h3>
            <p>Agents sleep after configurable idle time (default 30 min) and wake on demand. State persists through R2 sync. Pay only for active compute. No data loss during transitions.</p>
          </div>
          <div class="card">
            <div class="icon">🛡️</div>
            <h3>DLP Redaction Pipeline</h3>
            <p>Built-in data loss prevention strips sensitive data (PII, PHI, financial data) before it leaves the sandbox. Redaction actions are logged in the proof bundle.</p>
          </div>
        </div>
      </div>
    </section>

    <section class="section" style="background:var(--bg-alt)">
      <div class="wrap">
        <div class="stats">
          <div class="stat"><div class="num">100</div><div class="label">Concurrent containers (expandable)</div></div>
          <div class="stat"><div class="num">Zero</div><div class="label">Cross-tenant leakage</div></div>
          <div class="stat"><div class="num">Ed25519</div><div class="label">Per-agent identity</div></div>
          <div class="stat"><div class="num">5 min</div><div class="label">Health check interval</div></div>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="cta-banner">
          <h2>Deploy Secure AI Workers Today</h2>
          <p>Hardware-isolated, policy-enforced, cryptographically attested.</p>
          <a href="/contact" class="cta-btn cta-btn-lg">Talk to Sales</a>
          <a href="/guides/first-30-days" class="cta-btn cta-btn-outline cta-btn-lg" style="margin-left:.75rem">Deployment Guide</a>
        </div>
      </div>
    </section>`,
  });
}

export function consultingPage(): string {
  return layout({
    meta: {
      title: "Enterprise AI Consulting | Agent Strategy & Deployment | Claw EA",
      description: "Expert consulting for enterprise AI agent strategy, deployment, and operations. From proof of concept to production fleet. Custom agent configurations and compliance mapping.",
      path: "/consulting",
    },
    breadcrumbs: [{ name: "Home", path: "/" }, { name: "Consulting", path: "/consulting" }],
    body: `
    <section class="hero">
      <div class="wrap">
        <span class="badge badge-purple">Professional Services</span>
        <h1>Enterprise AI Agent Consulting</h1>
        <p class="sub">From strategy to production. Our team helps enterprises design, deploy, and operate AI agent fleets that meet compliance requirements and deliver measurable ROI.</p>
        <div class="actions">
          <a href="/contact" class="cta-btn cta-btn-lg">Book a Consultation</a>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="grid-3">
          <div class="card">
            <div class="icon">🧭</div>
            <h3>AI Agent Strategy</h3>
            <p>Identify the highest-ROI use cases for your industry. Map agent capabilities to business processes. Design the deployment roadmap.</p>
          </div>
          <div class="card">
            <div class="icon">🚀</div>
            <h3>Deployment Services</h3>
            <p>Custom agent templates. Work Policy Contract design. Model routing configuration. Channel integration setup. We get your first fleet running in days, not months.</p>
          </div>
          <div class="card">
            <div class="icon">📊</div>
            <h3>Compliance Mapping</h3>
            <p>Map Claw EA controls to your regulatory framework (SOC 2, HIPAA, GDPR, FedRAMP, PCI DSS). Pre-audit documentation. Auditor briefing support.</p>
          </div>
          <div class="card">
            <div class="icon">🔧</div>
            <h3>Custom Development</h3>
            <p>Custom OpenClaw skills for your workflows. Bespoke agent templates. SIEM and GRC integrations. API integrations with your existing tools.</p>
          </div>
          <div class="card">
            <div class="icon">📈</div>
            <h3>Optimization</h3>
            <p>Model routing optimization to reduce costs 40-60%. Agent fleet right-sizing. Performance tuning. Budget control configuration.</p>
          </div>
          <div class="card">
            <div class="icon">🎓</div>
            <h3>Training</h3>
            <p>Train your team on agent management, WPC design, proof bundle verification, and fleet operations. Role-based training for admins, developers, and compliance officers.</p>
          </div>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="wrap">
        <div class="cta-banner">
          <h2>Start With a Free Assessment</h2>
          <p>30-minute call to identify your top AI agent use cases and compliance requirements.</p>
          <a href="/contact" class="cta-btn cta-btn-lg">Book a Consultation</a>
        </div>
      </div>
    </section>`,
  });
}

export function aboutPage(): string {
  return layout({
    meta: {
      title: "About Claw Bureau | Enterprise AI Trust Infrastructure",
      description: "Claw Bureau builds trust infrastructure for the AI agent economy. Verified execution, cryptographic attestation, and enterprise-grade security.",
      path: "/about",
    },
    breadcrumbs: [{ name: "Home", path: "/" }, { name: "About", path: "/about" }],
    body: `
    <section class="section content-page">
      <div class="wrap">
        <h1>Building Trust Infrastructure for AI Agents</h1>
        <p class="lead">Claw Bureau exists because the world is deploying AI agents without the infrastructure to verify what those agents actually do. We are changing that.</p>

        <h2>The Problem</h2>
        <p>Enterprises are deploying AI agents into production workflows. These agents access sensitive data, make decisions, and interact with customers. But there is no way to prove what an agent did, where it ran, or whether policy controls were active during execution.</p>
        <p>Traditional logging is mutable. Traditional security is perimeter-based. Neither works for autonomous AI agents that operate across models, channels, and data sources.</p>

        <h2>Our Approach</h2>
        <p>Claw Bureau builds cryptographic verification infrastructure for AI agent operations. Every agent action produces a signed, tamper-evident record. Proof bundles can be independently verified by auditors, regulators, or counterparties without trusting the platform operator.</p>

        <h2>The Ecosystem</h2>
        <p>Claw EA is part of the broader Claw Bureau ecosystem:</p>
        <ul>
          <li><strong><a href="https://clawverify.com">clawverify.com</a></strong> - Signature verification API</li>
          <li><strong><a href="https://clawproxy.com">clawproxy.com</a></strong> - Gateway receipts and Proof of Harness</li>
          <li><strong><a href="https://clawbounties.com">clawbounties.com</a></strong> - AI agent bounty marketplace</li>
          <li><strong><a href="https://clawescrow.com">clawescrow.com</a></strong> - Payment escrow for agent work</li>
          <li><strong><a href="https://clawcuts.com">clawcuts.com</a></strong> - Revenue sharing infrastructure</li>
          <li><strong><a href="https://clawbureau.com">clawbureau.com</a></strong> - Ecosystem hub</li>
        </ul>

        <h2>Built on OpenClaw</h2>
        <p>Claw EA deploys managed OpenClaw instances. OpenClaw is a personal AI assistant platform with 20+ channel integrations, multi-model support, plugin architecture, and hybrid memory search. We add the enterprise trust layer: sandboxed execution, Work Policy Contracts, cryptographic attestation, and fleet management.</p>
      </div>
    </section>`,
  });
}
