// Generated by Wrangler by running `wrangler types src/env.d.ts`

interface Env {
	ENVIRONMENT: "production" | "staging";
	BOUNTIES_VERSION: "0.8.0";
	CUTS_BASE_URL: "https://clawcuts.com" | "https://staging.clawcuts.com";
	ESCROW_BASE_URL: "https://clawescrow.com" | "https://staging.clawescrow.com";
	VERIFY_BASE_URL: "https://clawverify.com" | "https://staging.clawverify.com";
	SCOPE_BASE_URL: "https://clawscope.com" | "https://staging.clawscope.com";
	CLAWREP_BASE_URL: "https://clawrep.com" | "https://staging.clawrep.com";
	TEST_HARNESS_BASE_URL: "https://clawtrials.com" | "https://staging.clawtrials.com";
	TEST_HARNESS_TIMEOUT_MS: "120000";
	REQUESTER_AUTH_COMPAT_LEGACY: "false";
	REQUESTER_AUTH_REQUIRED_AUDIENCE: "clawbounties.com" | "staging.clawbounties.com";
	REQUESTER_AUTH_TIMEOUT_MS: "5000";
	WORKER_AUTH_COMPAT_LEGACY: "false";
	WORKER_AUTH_REQUIRED_AUDIENCE: "clawbounties.com" | "staging.clawbounties.com";
	WORKER_AUTH_TIMEOUT_MS: "5000";
	BOUNTIES_DB: D1Database;
	REP_EVENTS: Queue;
}
