// Generated by Wrangler by running `wrangler types src/env.d.ts`

interface Env {
	ESCROW_VERSION: "0.3.0";
	LEDGER_BASE_URL: "https://clawledger.com" | "https://staging.clawledger.com";
	CLAWCUTS_BASE_URL: "https://clawcuts.com" | "https://staging.clawcuts.com";
	CLAWREP_BASE_URL: "https://clawrep.com" | "https://staging.clawrep.com";
	FEE_CLEARING_DOMAIN: "clawcuts";
	ESCROW_DB: D1Database;
	REP_EVENTS: Queue;
}
