// Generated by Wrangler by running `wrangler types src/env.d.ts`

interface Env {
	REP_CACHE: KVNamespace;
	REP_VERSION: "0.2.0";
	REP_DECAY_DAILY_RATE: "0.02";
	REP_REVIEWER_CACHE_TTL_SECONDS: "120";
	REP_REVIEWER_HISTORY_DAYS: "30";
	REP_REVIEWER_COOLDOWN_HOURS: "12";
	REP_DB: D1Database;
	REP_EVENTS: Queue;
}
